theme: jekyll-theme-minimal
title: MOStay
logo: https://raw.githubusercontent.com/m-soro/mostay/main/files/loho4.png
description: Easily get MOStay availability of multiple Mandarin Oriental properties.
